project:
  title: "DS 1001 Active Learning Modules"
  type: book
  output-dir: docs

book:
  title: "DS 1001 Active Learning Modules"
  author: "R.C. Alvarado"
  date: "8/23/2023"
  site-url: https://ontoligent.github.io/sds-active-learning-modules
  repo-url: https://github.com/ontoligent/sds-active-learning-modules

  chapters:
    - index.qmd
    - rubric.md
    - part: "M02: Basic Python"
      chapters:
        - modules/M02_BasicPython/M02A-UsingPython.ipynb
        - modules/M02_BasicPython/M02B-VariablesAndData.ipynb
    - part: "M03: Control Structures"
      chapters:
        - modules/M03_ControlStructures/M03-00-Goals.ipynb
        - modules/M03_ControlStructures/M03-01-Readings.ipynb
        - modules/M03_ControlStructures/M03-02-IterablesAndIterators.ipynb
        - modules/M03_ControlStructures/M03-03-ControlStructures.ipynb
        - modules/M03_ControlStructures/M03-04-Comprehensions.ipynb
        - modules/M03_ControlStructures/M03-Exercises.html
        - modules/M03_ControlStructures/M03-Quiz.md
        - modules/M03_ControlStructures/M03-HW.ipynb
    # - part: "M04: Functions"
    #   chapters:
    #     - modules/M04_PythonFunctions/
    #     - modules/M04_PythonFunctions/
    #     - modules/M04_PythonFunctions/
    #     - modules/M04_PythonFunctions/
    #     - modules/M04_PythonFunctions/
    #     - modules/M04_PythonFunctions/
    #     - modules/M04_PythonFunctions/
    #     - modules/M04_PythonFunctions/
    #     - modules/M04_PythonFunctions/
        
    
    # - part: index.qmd                                                     # Preface
    #   chapters:
    #   - rubric.md
    # - part: modules/M02_BasicPython/M02-00-1-Intro.qmd                    # M02 
    #   chapters:
    #     - part: "Running Python"
    #     chapters:
    #       - modules/M02_BasicPython/Activities/M02-00-4-ActivityHelloWorld.qmd
    #       - modules/M02_BasicPython/Activities/M02-00-5-ActivityJupyterLabOnRivanna.qmd
    #     - part: "Data Types and Structures"
    #     chapters:
    #       - modules/M02_BasicPython/M02-00-2-OnData.qmd
    #       - modules/M02_BasicPython/M02-00-3-ObjectTypes.qmd
    #       - modules/M02_BasicPython/M02-01-DataTypes.ipynb
    #       - modules/M02_BasicPython/M02-02-Numbers.ipynb
    #       - modules/M02_BasicPython/M02-03-Booleans.ipynb
    #       - modules/M02_BasicPython/M02-04-Strings.ipynb
    #       - modules/M02_BasicPython/M02-05-Structures.ipynb
    #       - modules/M02_BasicPython/Activities/M02-99-1-Exercises.ipynb
    #       - modules/M02_BasicPython/Quiz/M02-99-2-Quiz.txt
    #       - modules/M02_BasicPython/HW/M02-HW.ipynb
    # - part: modules/M03_ControlStructures/M03-00-1-Intro.qmd              # M03
    #   chapters:
    #     - modules/M03_ControlStructures/M03-00-2-ValsVarsExpressionsStatements.qmd
    #     - modules/M03_ControlStructures/M03-01-ControlStructures.ipynb
    #     - modules/M03_ControlStructures/M03-01-ControlStructures.ipynb
    #     - modules/M03_ControlStructures/M03-02-IterablesAndIterators.ipynb
    #     - modules/M03_ControlStructures/M03-03-Comprehensions.ipynb
    #     - modules/M03_ControlStructures/M03-99-1-Exercises.ipynb
    #     - modules/M03_ControlStructures/M03-99-2-Quiz.txt
    #     - modules/M03_ControlStructures/HW/M03-HW.ipynb
    # - part: modules/M04_PythonFunctions/M04-00-1-Intro.qmd                 # M04
    #   chapters:
    #     - modules/M04_PythonFunctions/M04-01-Importing.ipynb
    #     - modules/M04_PythonFunctions/M04-02-Functions.ipynb
    #     - modules/M04_PythonFunctions/M04-03-LambdaFunctions.ipynb
    #     - modules/M04_PythonFunctions/M04-04-RecursiveFunctions.ipynb
    #     - modules/M04_PythonFunctions/M04-05-Scope.ipynb
    #     - modules/M04_PythonFunctions/M04-06-FunctionsCallingFunctions.ipynb
    #     - modules/M04_PythonFunctions/M04-99-1-Exercises.ipynb
    #     - modules/M04_PythonFunctions/M04-99-2-Quiz.txt
    #     - modules/M04_PythonFunctions/HW/M04-HW.ipynb
  sidebar:
    style: docked
    # style: floating
    background: light
    collapse-level: 1
    subtitle: Summer 2023

bibliography: references.bib

comments:
  hypothesis: true

format:
  html:
    toc: true
    theme: cosmo
    number-sections: false
    fig-cap-location: bottom
    link-external-icon: true
    link-external-newwindow: true
  # pdf:
  #   documentclass: scrreport    
