project:
  title: "DS 1001 Active Learning Modules"
  type: book
  output-dir: docs

book:
  title: "DS 1001 Active Learning Modules"
  author: "R.C. Alvarado"
  date: "8/23/2023"
  site-url: https://ontoligent.github.io/sds-active-learning-modules
  repo-url: https://github.com/ontoligent/sds-active-learning-modules

  chapters:
    - index.qmd
    - rubric.md
    - part: "M02: Basic Python"
      chapters:
        - modules/M02_BasicPython/M02A-UsingPython.ipynb
        - modules/M02_BasicPython/M02B-VariablesAndData.ipynb
    - part: "M03: Control Structures"
      chapters:
        - modules/M03_ControlStructures/M03-00-Goals.ipynb
        - modules/M03_ControlStructures/M03-01-Readings.ipynb
        - modules/M03_ControlStructures/M03-02-IterablesAndIterators.ipynb
        - modules/M03_ControlStructures/M03-03-ControlStructures.ipynb
        - modules/M03_ControlStructures/M03-04-Comprehensions.ipynb
        - modules/M03_ControlStructures/M03-Exercises.html
        - modules/M03_ControlStructures/M03-Quiz.md
        - modules/M03_ControlStructures/M03-HW.ipynb
    - part: "M04: Functions"
      chapters:
        - modules/M04_PythonFunctions/M04-00-Goals.ipynb
        - modules/M04_PythonFunctions/M04-01-Readings.ipynb
        - modules/M04_PythonFunctions/M04-02-Importing.ipynb
        - modules/M04_PythonFunctions/M04-03-Functions.ipynb
        - modules/M04_PythonFunctions/M04-04-LambdaFunctions.ipynb
        - modules/M04_PythonFunctions/M04-05-RecursiveFunctions.ipynb
        - modules/M04_PythonFunctions/M04-06-Scope.ipynb
        - modules/M04_PythonFunctions/M04-07-FunctionsCallingFunctions.ipynb
        - modules/M04_PythonFunctions/M04-08-Exercises.html
        - modules/M04_PythonFunctions/M04-Quiz.md
        - modules/M04_PythonFunctions/M04-HW.ipynb
    
  sidebar:
    style: docked
    # style: floating
    background: light
    collapse-level: 1
    subtitle: Summer 2023

bibliography: references.bib

comments:
  hypothesis: true

format:
  html:
    toc: true
    theme: cosmo
    number-sections: false
    fig-cap-location: bottom
    link-external-icon: true
    link-external-newwindow: true
  # pdf:
  #   documentclass: scrreport    
