# Reading: Introducing Python

## Overview

This the first module in a module sequence designed to introduce undergraduate students to programming with Python from the perspective of Data Science.

## Prerequisites

- Knowledge of Python is not required.
- Knowledge of other programming knowledge is not required but helpful.
- Access to a computer with Python installed is required.
- Access to a computer with Jupyter Lab or Notebook installed is required.
- Knowledge of Git and GitHub is not required but helpful.
- Knowledge of Data Science is not required.

## Learning Goals

After completing this module, the student should:

- Become acquainted with the Python programming language.
- Understand the concept of data-centric programming.
- Understand the distinction between data types and data structures.
- Become familiar with the most basic basic data types and their operations.
- Become familiar with the most basic basic data structures and their operations.

## Learning Outcomes

In terms of specific knowledge, skills, and abilities, after completing this module students should be able to:

- Describe the idea of programming from the perspective of Data Science.
- Know how write a simple Python script and run it from a notebook or from the command line.
- Know the distinction between a literal value and a variable.
- Know to assign a value to a variable.
- Know the names of primary data types in Python -- floats, integers, booleans, and strings -- and how to represent literal values for each.
- Know the basic operators, functions, and methods associated with each data type.
- Understand the distinction between and operator, function, and method.
- Know how to convert a value of one type to another.
- Know how to find our the type of value or variable.
- Know Python's built-in data structures -- tuples, lists, dictionaries, and sets.
- Know the basic operators, methods, and functions associated with each data structure.
- Understand the concept of an expression and its relation to literals, variables, operators, and functions.

## Readings

### Required

Before attempting to complete the activities in this module, read the following:

- [Katz and Katz 2019, Section 1, Preparing the Workspace](https://learning.oreilly.com/library/view/learn-python-by/9781789535365/8f352965-cebb-43c0-b2ca-0f6bf944899e.xhtml)
- [Lutz, Learning Python, Part I: Getting Started, Chapter 2](https://learning.oreilly.com/library/view/learning-python-5th/9781449355722/ch02.html)
- [Lutz, Learning Python, Part I: Getting Started, Chapter 3](https://learning.oreilly.com/library/view/learning-python-5th/9781449355722/ch03.html)
- [Lutz, Learning Python, Part II: Types and Operations, Chapters 4--9](https://learning.oreilly.com/library/view/learning-python-5th/9781449355722/part02.html)

### Optional

These readings are not required but helpful, especially as resources to consult while completing or reviewing your work.

- [Katz and Katz 2019, Section 1, First Steps in Coding&mdash;Variables and Data Types](https://learning.oreilly.com/library/view/learn-python-by/9781789535365/5fea535c-b144-4c8b-b20b-0a0ee1c1f157.xhtml)
- [Built-in Types (Official)](https://docs.python.org/3/library/stdtypes.html)
- [Python Data Types (GFG)](https://www.geeksforgeeks.org/python-data-types/)
- [Python Operators (W3S)](https://www.w3schools.com/python/python_operators.asp)
- [Immutable vs Mutable Data Types in Python (Medium)](https://towardsdatascience.com/immutable-vs-mutable-data-types-in-python-e8a9a6fcfbdc)
